      PROGRAM HCUST
C     PROGRAM TO ACT AS A FRONT END TO THE HARMONIC ANALYSIS ROUTINES.
C     Robert Grumbine 8-25-86.
C     CUSTOMIZED 11-6-86 TO BE FOR A 'SMALL' NUMBER OF DATA POINTS,
C       AND TO EXAMINE MULTIPLE FILES AT THE SAME SET OF FREQUENCIES.  B
      INTEGER M, N
      REAL A(400), B(400), FREQ(400)
      REAL X(10000)

      INTEGER I, UNIT
      CHARACTER*60 FNAME
      LOGICAL YES

      REAL PI
      PARAMETER (PI = 3.141592654)

      UNIT = 12

      OPEN (5, FILE='HIN', FORM='FORMATTED', STATUS='OLD')

CI    PRINT *,'HOW MANY FREQUENCIES DO YOU WANT TO ANALYZE?'
      READ (*,9001) N

      DO 1000 I = 1, N
CI      PRINT *,'ENTER THE FREQUENCY (CPH)'
        READ (*,9002) FREQ(I)
        FREQ(I) = FREQ(I) * 2.*PI
 1000 CONTINUE

 3000 CONTINUE
C       REPEAT UNTIL LOOP, USE THE GIVEN SET OF FREQUENCIES FOR ALL FILE
        UNIT = UNIT + 1

CI      PRINT *,'HOW MANY DATA POINTS ARE THERE?'
        READ (*,9001) M

        CALL READIN(X, M)

C       FIND TO BEST FIT AMPLITUDES FOR THE GIVEN FREQUENCIES.
        IF (FREQ(1) .EQ. 0.0) THEN
          CALL HARMRM(X, M, FREQ, A, B, N)
         ELSE
          CALL HARMRN(X, M, FREQ, A, B, N)
        ENDIF

C       WRITE OUT RESULTS:
CI      PRINT *,'WHAT DO YOU WANT TO CALL THE HARMONIC DATA FILE?'
        READ (*,9003) FNAME
        OPEN (UNIT, FILE=FNAME, FORM='FORMATTED', STATUS='NEW')

        DO 2000 I = 1, N
C         WRITE (*,9002) FREQ(I)/2./PI, (A(I)*A(I)+B(I)*B(I))**.5,
C    1              ATAN2(B(I),A(I))
          WRITE (UNIT,9002) FREQ(I)/2./PI, (A(I)*A(I)+B(I)*B(I))**.5,
     1              ATAN2(B(I),A(I))
 2000   CONTINUE

C       SUBTRACT THE ANALYZED COMPONENTS FROM THE DATA.
CI      PRINT *,'DO YOU WANT TO SUBTRACT THE BEST FIT HARMONICS?'
        IF (YES(.FALSE.)) THEN
          CALL DEMOD (A, B, FREQ, N, X, M)

          PRINT *,'WHAT DO YOU WANT TO CALL THE RESIDUAL FILE?'
          CALL RITOUT(X, M, 11)

        ENDIF

        CLOSE (UNIT, STATUS='KEEP')
        PRINT *,'DO YOU WANT TO PROCESS ANOTHER FILE?'
      IF (YES(.FALSE.)) GO TO 3000

 9001 FORMAT (BN, I5)

 9002 FORMAT (3E14.6)

 9003 FORMAT (A60)

      END
